### ISSUE TITLE
oracle java installation error

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-elasticsearch#5]
Oracle repository seems to be no longer providing the
oracle-java8-installer package required by this role by default, producing an error and breaking the apt installer (subsequent apt-get commands issue keep trying to install it)

Workaround:
 * do a `dpkg -r oracle-java8-installer` on the affected machine to fix apt
 * Install openjdk instead of oracle java  (ref. #3), see https://github.com/artefactual/deploy-pub/pull/47 for an example

**Comment by sevein** [comment]
Fixed in #6.
