### ISSUE TITLE
Problem: Errors when upgrading to Elasticsearch 5.x

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-elasticsearch#7]
AtoM 2.5 needs Elasticsearch 5.x. 

Several changes are needed to upgrade to Elasticsearch 5.x with this ansible role. Upgrading is not about just changing the variable elasticsearch_version to '5.X.Y' version and running the role.

**Comment by mamedin** [comment]
These are the steps that I followed to upgrade Elasticsearch from 1.7.x to 5.3.3 on ubuntu 16:

I used these variables on the host vars.yml file: 

```
elasticsearch_version: "5.3.3"
elasticsearch_download_url: "https://artifacts.elastic.co/downloads/elasticsearch"
```

Changes on elasticsearch settings after running the role:

1) /etc/default/elasticsearch: `ES_HEAP_SIZE=2048m` is no longer supported, use `ES_JAVA_OPTS="-Xms2048m -Xmx2048m"` instead.
2) /etc/elasticsearch/logging.yml is not used, we can delete or move to /tmp: `mv /etc/elasticsearch/logging.yml  /tmp/` (it is a warning, not an error)
3) /etc/elasticsearch/elasticsearch.yml: `path.plugins` and `path.work` variables are no longer supported. I commented out the following lines:
	#path.plugins: /usr/share/elasticsearch/plugins
	#path.work: /tmp/elasticsearch
4) The old atom index should be deleted to avoid this error:
```
 Error injecting constructor, java.lang.IllegalStateException: The index [[atom/3HPZlTCaRwq43AysOGt0AA]] was created with version [1.7.5]but the minimum compatible version is [2.0.0-beta1]. It should be re-indexed in Elasticsearch 2.x before upgrading to 5.3.3.
```

    - Deleting before upgrading using curator or curl:
        curl -XDELETE 'http://localhost:9200/atom'
    
    - Or delete elasticsearch index directory after the upgrade:
         sudo rm -rf /var/lib/elasticsearch/elasticsearch/nodes to avoid this error: 

After the upgrade, run `php symfony search:populate` to recreate the atom index.

**Comment by scollazo** [comment]
Closed by https://github.com/artefactual-labs/ansible-elasticsearch/pull/16
